//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class agent
    {
        public string matricule { get; set; }
        public string nom_agent { get; set; }
        public string prenom_agent { get; set; }
        public string photo_agent { get; set; }
        public string adress { get; set; }
        public string login { get; set; }
        public string pass { get; set; }
        public string role { get; set; }
        public int matri { get; set; }
    }
}
