//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contibuable
    {
        public int id_contibuable { get; set; }
        public string nom_contibuable { get; set; }
        public string prenom_contibuable { get; set; }
        public string cni_contibuable { get; set; }
        public string photo_contibuable { get; set; }
        public string telephon_contibuable { get; set; }
        public string activite { get; set; }
        public string adresse { get; set; }
        public string login { get; set; }
        public string pass { get; set; }
        public Nullable<int> etat { get; set; }
    }
}
