//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class quitance
    {
        public int id_taxe { get; set; }
        public Nullable<int> id_contri { get; set; }
        public Nullable<int> taux { get; set; }
        public string anne { get; set; }
        public string date { get; set; }
        public string etat { get; set; }
        public string bordereau { get; set; }
        public Nullable<int> matricule { get; set; }
    }
}
